AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  myBlog

  Sample SAM Template for myBlog

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  PostGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: post-get/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          TableName: !Ref DynamoDBTable
      Events:
        PostGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /post/{post_id}
            Method: get
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
  PostsListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: posts-list/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          TableName: !Ref DynamoDBTable
      Events:
        PostsListGet:
          Type: Api
          Properties:
            Path: /
            Method: get
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
  PutPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: put-post/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          TableName: !Ref DynamoDBTable
      Events:
        PostsListGet:
          Type: Api
          Properties:
            Path: /post/{post_id}
            Method: put
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON



  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PostGetApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  PostGetFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PostGetFunction.Arn
  PostGetFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PostGetFunctionRole.Arn
